apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-xq8j
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0016-tenant/tkrw-pr712-0075-0016-app/devfile-sample-xq8j@sha256:4cddc293a31bfa5d9d62167bc2bf6fdd938865a478dc2346da9b6b35d0304b51
        name: my-nodejs
        resources: {}
status: {}
